# Generated by Django 2.2.6 on 2019-10-03 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecotox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecotox_airu', models.FloatField(blank=True, default=0, null=True)),
                ('ecotox_airc', models.FloatField(blank=True, default=0, null=True)),
                ('ecotox_waterc', models.FloatField(blank=True, default=0, null=True)),
                ('ecotox_seawaterc', models.FloatField(blank=True, default=0, null=True)),
                ('ecotox_nat_soilc', models.FloatField(blank=True, default=0, null=True)),
                ('ecotox_agr_soilc', models.FloatField(blank=True, default=0, null=True)),
                ('ecotox_flag', models.CharField(choices=[('N/A', 'n/a'), ('RECOMMENDED', 'Recommended'), ('INTERIM', 'Interim')], default='N/A', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='FossilFuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cf', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hhcf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hhcf_urban_air_cancer', models.FloatField(blank=True, default=0, null=True)),
                ('hhcf_urban_air_noncanc', models.FloatField(blank=True, default=0, null=True)),
                ('hhcf_rural_air_cancer', models.FloatField(blank=True, default=0, null=True)),
                ('hhcf_rural_air_noncanc', models.FloatField(blank=True, default=0, null=True)),
                ('hhcf_freshwater_cancer', models.FloatField(blank=True, default=0, null=True)),
                ('hhcf_freshwater_noncanc', models.FloatField(blank=True, default=0, null=True)),
                ('hhcf_seawater_cancer', models.FloatField(blank=True, default=0, null=True)),
                ('hhcf_seawater_noncanc', models.FloatField(blank=True, default=0, null=True)),
                ('hhcf_natsoil_cancer', models.FloatField(blank=True, default=0, null=True)),
                ('hhcf_natsoil_noncanc', models.FloatField(blank=True, default=0, null=True)),
                ('hhcf_agrsoil_cancer', models.FloatField(blank=True, default=0, null=True)),
                ('hhcf_agrsoil_noncanc', models.FloatField(blank=True, default=0, null=True)),
                ('hhcf_carcinogenic_flag', models.CharField(choices=[('N/A', 'n/a'), ('RECOMMENDED', 'Recommended'), ('INTERIM', 'Interim')], default='N/A', max_length=12)),
                ('hhcf_noncarcinogenic_flag', models.CharField(choices=[('N/A', 'n/a'), ('RECOMMENDED', 'Recommended'), ('INTERIM', 'Interim')], default='N/A', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cas', models.CharField(max_length=32)),
                ('formatted_cas', models.CharField(max_length=32)),
                ('global_warming_air', models.FloatField(blank=True, default=0, null=True)),
                ('acidification_air', models.FloatField(blank=True, default=0, null=True)),
                ('hh_particulate_air', models.FloatField(blank=True, default=0, null=True)),
                ('eutrophication_air', models.FloatField(blank=True, default=0, null=True)),
                ('eutrophication_water', models.FloatField(blank=True, default=0, null=True)),
                ('ozone_depletion_air', models.FloatField(blank=True, default=0, null=True)),
                ('smog_air', models.FloatField(blank=True, default=0, null=True)),
                ('ecotox', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='substances.Ecotox')),
                ('hhcf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='substances.Hhcf')),
            ],
        ),
    ]
