# Generated by Django 2.2.6 on 2019-10-02 19:38
# pylint: skip-file

import os
from django.core import serializers
from django.db import migrations, transaction
from django.db.utils import IntegrityError

fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))
fixture_substances = 'substances_initial_data.json'
fixture_units = 'unit.json'

def load_fixture_substances(_apps, _schema_editor):
    """Load data from a fixture when running migrations"""
    load_fixture(_apps, _schema_editor, fixture_substances)

def load_fixture_units(_apps, _schema_editor):
    """Load data from a fixture when running migrations"""
    load_fixture(_apps, _schema_editor, fixture_units)

def load_fixture(_apps, _schema_editor, fixture_filename):
    """Load data from a fixture when running migrations"""
    fixture_file = os.path.join(fixture_dir, fixture_filename)
    fixture = open(fixture_file, 'rb')
    objects = serializers.deserialize('json', fixture, ignorenonexistent=True)
    for obj in objects:
        try:
            with transaction.atomic():
                obj.save()
        except IntegrityError:
            pass    # Ignore if duplicate obj already exists in db
    fixture.close()


class Migration(migrations.Migration):

    dependencies = [
        ('substances', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture_substances),
        migrations.RunPython(load_fixture_units),
    ]
