# Generated by Django 4.0.6 on 2022-07-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0002_load_fixtures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemical',
            name='eutrophication_air',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='eutrophication_water',
        ),
    ]
