# Generated by Django 2.2.6 on 2019-10-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substances', '0002_loaddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='chemical_unit',
            field=models.BooleanField(default=False),
        ),
    ]
