# Generated by Django 2.2.3 on 2019-09-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add class docstring."""

    dependencies = [
        ('substances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecotox',
            name='ecotox_agr_soilc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ecotox',
            name='ecotox_airc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ecotox',
            name='ecotox_airu',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ecotox',
            name='ecotox_nat_soilc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ecotox',
            name='ecotox_seawaterc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ecotox',
            name='ecotox_waterc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hhcf',
            name='hhcf_agrsoil_cancer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hhcf',
            name='hhcf_agrsoil_noncanc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hhcf',
            name='hhcf_freshwater_cancer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hhcf',
            name='hhcf_freshwater_noncanc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hhcf',
            name='hhcf_natsoil_cancer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hhcf',
            name='hhcf_natsoil_noncanc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hhcf',
            name='hhcf_rural_air_cancer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hhcf',
            name='hhcf_rural_air_noncanc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hhcf',
            name='hhcf_seawater_cancer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hhcf',
            name='hhcf_seawater_noncanc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hhcf',
            name='hhcf_urban_air_cancer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hhcf',
            name='hhcf_urban_air_noncanc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='acidification_air',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='eutrophication_air',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='eutrophication_water',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='global_warming_air',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='hh_particulate_air',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='ozone_depletion_air',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='smog_air',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
