# Generated by Django 2.1.5 on 2019-02-19 18:16
# pylint: disable=line-too-long,missing-docstring,invalid-name

"""
Custom migration created to import initial
data and other required data from fixture files.
"""

import os
from django.core import serializers
from django.db import migrations, transaction
from django.db.utils import IntegrityError

fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))
fixture_filename = 'substances_initial_data.json'


def load_fixture(_apps, _schema_editor):
    """Load data from a fixture when running migrations"""
    fixture_file = os.path.join(fixture_dir, fixture_filename)
    fixture = open(fixture_file, 'rb')
    objects = serializers.deserialize('json', fixture, ignorenonexistent=True)
    for obj in objects:
        try:
            with transaction.atomic():
                obj.save()
        except IntegrityError:
            pass    # Ignore if duplicate obj already exists in db
    fixture.close()


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_auto_20190802_1418'),
        ('products', '0001_initial'),
        ('products', '0002_product_project'),
        ('projects', '0001_initial'),
        ('substances', '0001_initial'),
        ('substances', '0002_auto_20190912_1356'),
        ('support', '0001_initial'),
        ('support', '0002_auto_20170829_1252'),
        ('support', '0003_auto_20180409_0948'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
