# Generated by Django 2.2.6 on 2019-10-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=31, null=True)),
                ('organization', models.CharField(blank=True, max_length=127, null=True)),
                ('org_unit', models.CharField(blank=True, max_length=63, null=True)),
                ('contact', models.CharField(blank=True, max_length=127, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=31, null=True)),
                ('scope', models.CharField(blank=True, choices=[('cradle_to_grave', 'Cradle to Grave'), ('cradle_to_entry_gate', 'Cradle to Entry Gate'), ('entry_gate_to_exit_gate', 'Entry Gate to Exit Gate'), ('exit_gate_to_grave', 'Exit Gate to Grave')], max_length=127, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('functional_unit', models.CharField(blank=True, max_length=31, null=True)),
            ],
        ),
    ]
