# Generated by Django 2.2.6 on 2019-10-04 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='name',
            new_name='chemical',
        ),
        migrations.RenameField(
            model_name='release',
            old_name='media',
            new_name='release_media',
        ),
        migrations.RenameField(
            model_name='release',
            old_name='quantity',
            new_name='release_quantity',
        ),
        migrations.RenameField(
            model_name='release',
            old_name='unit',
            new_name='release_unit',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='media',
            new_name='resource_media',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='quantity',
            new_name='resource_quantity',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='unit',
            new_name='resource_unit',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='name',
            new_name='substance_type',
        ),
        migrations.AddField(
            model_name='resource',
            name='process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Process'),
            preserve_default=False,
        ),
    ]
