# Generated by Django 2.2.5 on 2019-09-27 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Add class docstring."""

    dependencies = [
        ('projects', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
            preserve_default=False,
        ),
    ]
