# Generated by Django 2.2.6 on 2019-10-02 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_load_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifecyclestage',
            name='processes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stages',
        ),
        migrations.CreateModel(
            name='LifeCycleStageEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('lifecyclestage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.LifeCycleStage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
