# Generated by Django 2.2.6 on 2019-10-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191003_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
