# Generated by Django 2.2.6 on 2019-10-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substances', '0002_auto_20191002_1538'),
        ('products', '0004_auto_20191003_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceReleaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('type', models.CharField(max_length=63)),
            ],
        ),
        migrations.RemoveField(
            model_name='substanceentry',
            name='media',
        ),
        migrations.RemoveField(
            model_name='substanceentry',
            name='substance',
        ),
        migrations.RemoveField(
            model_name='process',
            name='resource_release',
        ),
        migrations.RemoveField(
            model_name='resourcerelease',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resourcerelease',
            name='substances',
        ),
        migrations.AddField(
            model_name='resourcerelease',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Media'),
        ),
        migrations.AddField(
            model_name='resourcerelease',
            name='process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Process'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcerelease',
            name='quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='resourcerelease',
            name='substance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='substances.Substance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcerelease',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='ResourceReleaseOption',
        ),
        migrations.DeleteModel(
            name='SubstanceEntry',
        ),
        migrations.AddField(
            model_name='resourcerelease',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.ResourceReleaseType'),
            preserve_default=False,
        ),
    ]
