# Generated by Django 2.2.6 on 2019-10-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191002_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifecyclestageentry',
            name='name',
        ),
    ]
