# Generated by Django 2.2.6 on 2019-10-02 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_lifecyclestageentry_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeCycleStageName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.AddField(
            model_name='lifecyclestage',
            name='product',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lifecyclestage',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.LifeCycleStageName'),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProcessName'),
        ),
        migrations.DeleteModel(
            name='LifeCycleStageEntry',
        ),
    ]
