# Generated by Django 2.2.6 on 2019-10-03 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191003_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='lifecyclestage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.LifeCycleStage'),
            preserve_default=False,
        ),
    ]
