# Generated by Django 2.2.6 on 2019-10-03 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substances', '0003_unit'),
        ('products', '0006_process_lifecyclestage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerelease',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='substances.Unit'),
            preserve_default=False,
        ),
    ]
