# coding=utf-8
# Generated by Django 2.0 on 2017-12-08 14:41
# pylint: disable=line-too-long,missing-docstring,invalid-name

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import support.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sent_to_email', models.CharField(blank=True, max_length=255, null=True)),
                ('requestor_first_name', models.CharField(blank=True, max_length=255)),
                ('requestor_last_name', models.CharField(blank=True, max_length=255)),
                ('requestor_email_address', models.EmailField(max_length=255)),
                ('request_subject', models.CharField(max_length=255)),
                ('request_details', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('response_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('the_name', models.CharField(blank=True, max_length=255, null=True)),
                ('the_description', models.TextField(blank=True, null=True)),
                ('weblink', models.CharField(blank=True, max_length=255, null=True)),
                ('ordering', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('make_public', models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True)),
                ('share_with_user_group', models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=support.models.get_support_storage_path)),
                ('the_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('length_of_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('is_closed', models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True)),
                ('the_description', models.TextField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('weblink', models.CharField(blank=True, max_length=255, null=True)),
                ('ordering', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('date_resolved', models.DateField(blank=True, null=True)),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.Priority')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='SupportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('the_name', models.CharField(blank=True, max_length=255, null=True)),
                ('the_description', models.TextField(blank=True, null=True)),
                ('weblink', models.CharField(blank=True, max_length=255, null=True)),
                ('ordering', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.AddField(
            model_name='support',
            name='support_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.SupportType'),
        ),
        migrations.AddField(
            model_name='support',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
