# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 16:52
# pylint: disable=line-too-long,missing-docstring,invalid-name
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='is_closed',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='make_public',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='share_with_user_group',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
    ]
